"""Autonomous Cross-Language Microservice Synthesis Engine.

Generates strongly-typed gRPC (.proto) service declarations, OpenAPI 3.0/3.1
specifications, and client/server adapter boilerplate in Python, TypeScript,
and Go directly from knowledge graph endpoints and schemas.
"""

from __future__ import annotations

import json
from pathlib import Path
import re
from typing import Any, Dict, List, Optional, Tuple

from agtoosa.core.model import Node, NodeType
from agtoosa.graph.store import GraphStore


class MicroserviceSynthesizer:
    """Synthesizes protocol schemas and polyglot microservice adapters from graph models."""

    def __init__(self, store: GraphStore, workspace_root: Optional[Path] = None):
        self.store = store
        self.workspace_root = (workspace_root or Path.cwd()).resolve()

    def discover_service_endpoints(
        self, service_name: Optional[str] = None
    ) -> Tuple[str, List[Dict[str, Any]], List[Dict[str, Any]]]:
        """Discover API endpoints and schemas for a named service or current repository."""
        nodes = self.store.get_all_nodes()

        inferred_name = service_name or self.workspace_root.name.lower().replace("-", "_")
        endpoints: List[Dict[str, Any]] = []
        schemas: List[Dict[str, Any]] = []

        for node in nodes:
            meta = node.get("metadata", {}) or {}
            node_type = node.get("node_type", "")

            # Identify REST or RPC endpoints
            is_endpoint = (
                meta.get("kind") in ("rest_endpoint", "grpc_method", "endpoint")
                or meta.get("protocol") in ("rest", "grpc")
                or "method" in meta
                or node.get("id", "").startswith("endpoint:")
            )

            if is_endpoint:
                # If service filter provided, verify match
                repo = meta.get("repo", "local")
                if service_name and service_name != "all" and service_name != repo and service_name != inferred_name:
                    continue
                endpoints.append(node)

            # Identify data schemas / models
            is_schema = (
                (node_type in (NodeType.CLASS, NodeType.TABLE) or node_type == "schema")
                and (meta.get("kind") in ("schema_model", "orm_model") or "schema" in node.get("id", "").lower())
            )
            if is_schema:
                schemas.append(node)

        return inferred_name, endpoints, schemas

    @staticmethod
    def _normalize_identifier(name: str) -> str:
        """Convert an endpoint route or operation name into a clean PascalCase identifier."""
        cleaned = re.sub(r"[^a-zA-Z0-9]", " ", name)
        words = cleaned.split()
        if not words:
            return "Operation"
        return "".join(w.capitalize() for w in words)

    @staticmethod
    def _normalize_route_and_method(endpoint: Dict[str, Any]) -> Tuple[str, str, str]:
        """Extract HTTP method, route, and clean operation ID from endpoint node."""
        meta = endpoint.get("metadata", {}) or {}
        method = (meta.get("method") or "GET").upper()
        route = meta.get("route") or f"/api/{endpoint.get('name', 'action')}"
        if not route.startswith("/"):
            route = "/" + route

        op_name = endpoint.get("name") or f"{method}_{route}"
        op_id = MicroserviceSynthesizer._normalize_identifier(op_name)
        return method, route, op_id

    def synthesize_proto(
        self,
        service_name: str,
        endpoints: List[Dict[str, Any]],
        schemas: Optional[List[Dict[str, Any]]] = None
    ) -> str:
        """Generate a complete, valid Protocol Buffers v3 (.proto) service definition."""
        clean_svc = self._normalize_identifier(service_name)
        if not clean_svc.endswith("Service"):
            svc_class_name = f"{clean_svc}Service"
        else:
            svc_class_name = clean_svc

        lines = [
            'syntax = "proto3";',
            "",
            f'package {service_name.lower()}.v1;',
            "",
            f'option go_package = "{service_name.lower()}/v1;{service_name.lower()}v1";',
            f'option java_package = "com.agtoosa.{service_name.lower()}.v1";',
            "",
            f"// {svc_class_name} generated by Agtoosa2 Microservice Synthesizer.",
            f"service {svc_class_name} {{"
        ]

        if not endpoints:
            # Fallback placeholder method
            lines.append("  // Default health check RPC")
            lines.append("  rpc HealthCheck (HealthCheckRequest) returns (HealthCheckResponse);")
        else:
            for ep in endpoints:
                _, _, op_id = self._normalize_route_and_method(ep)
                summary = ep.get("docstring") or f"RPC method for {op_id}"
                lines.append(f"  // {summary}")
                lines.append(f"  rpc {op_id} ({op_id}Request) returns ({op_id}Response);")

        lines.append("}")
        lines.append("")

        # Generate Request/Response messages
        if not endpoints:
            lines.append("message HealthCheckRequest {")
            lines.append("  string service = 1;")
            lines.append("}")
            lines.append("")
            lines.append("message HealthCheckResponse {")
            lines.append("  string status = 1;")
            lines.append("  int64 timestamp = 2;")
            lines.append("}")
            lines.append("")
        else:
            for ep in endpoints:
                _, route, op_id = self._normalize_route_and_method(ep)
                lines.append(f"message {op_id}Request {{")
                # Parse route parameters if any (e.g. /users/{id})
                params = re.findall(r"\{([a-zA-Z0-9_]+)\}", route)
                field_idx = 1
                for param in params:
                    lines.append(f"  string {param} = {field_idx};")
                    field_idx += 1
                if not params:
                    lines.append("  string query = 1;")
                    lines.append("  int32 page_size = 2;")
                lines.append("}")
                lines.append("")

                lines.append(f"message {op_id}Response {{")
                lines.append("  bool success = 1;")
                lines.append("  string message = 2;")
                lines.append("  bytes payload = 3;")
                lines.append("}")
                lines.append("")

        # Optional entity schemas
        if schemas:
            for sc in schemas:
                sc_name = self._normalize_identifier(sc.get("name", "Model"))
                lines.append(f"message {sc_name} {{")
                lines.append("  string id = 1;")
                lines.append("  string name = 2;")
                lines.append("  int64 created_at = 3;")
                lines.append("}")
                lines.append("")

        return "\n".join(lines)

    def synthesize_openapi(
        self,
        service_name: str,
        endpoints: List[Dict[str, Any]],
        schemas: Optional[List[Dict[str, Any]]] = None
    ) -> Dict[str, Any]:
        """Generate a valid OpenAPI 3.0.3 specification dictionary."""
        clean_name = service_name.replace("_", " ").title()

        spec: Dict[str, Any] = {
            "openapi": "3.0.3",
            "info": {
                "title": f"{clean_name} API",
                "version": "1.0.0",
                "description": f"Microservice API specification synthesized by Agtoosa2 for {service_name}."
            },
            "paths": {},
            "components": {
                "schemas": {
                    "StandardResponse": {
                        "type": "object",
                        "properties": {
                            "success": {"type": "boolean"},
                            "message": {"type": "string"},
                            "data": {"type": "object"}
                        }
                    }
                }
            }
        }

        if not endpoints:
            # Default health endpoint
            spec["paths"]["/health"] = {
                "get": {
                    "summary": "Service Health Check",
                    "operationId": "healthCheck",
                    "responses": {
                        "200": {
                            "description": "Service is healthy",
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/StandardResponse"}
                                }
                            }
                        }
                    }
                }
            }
        else:
            for ep in endpoints:
                method, route, op_id = self._normalize_route_and_method(ep)
                method_lower = method.lower()
                summary = ep.get("docstring") or f"{method} {route}"

                if route not in spec["paths"]:
                    spec["paths"][route] = {}

                # Path parameters
                params = []
                for p in re.findall(r"\{([a-zA-Z0-9_]+)\}", route):
                    params.append({
                        "name": p,
                        "in": "path",
                        "required": True,
                        "schema": {"type": "string"}
                    })

                op_spec: Dict[str, Any] = {
                    "summary": summary,
                    "operationId": op_id,
                    "tags": [service_name],
                    "responses": {
                        "200": {
                            "description": "Successful operation",
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/StandardResponse"}
                                }
                            }
                        }
                    }
                }
                if params:
                    op_spec["parameters"] = params

                if method in ("POST", "PUT", "PATCH"):
                    op_spec["requestBody"] = {
                        "required": True,
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "payload": {"type": "object"}
                                    }
                                }
                            }
                        }
                    }

                spec["paths"][route][method_lower] = op_spec

        if schemas:
            for sc in schemas:
                sc_name = self._normalize_identifier(sc.get("name", "Model"))
                spec["components"]["schemas"][sc_name] = {
                    "type": "object",
                    "properties": {
                        "id": {"type": "string"},
                        "name": {"type": "string"},
                        "created_at": {"type": "integer", "format": "int64"}
                    }
                }

        return spec

    def synthesize_server_adapter(
        self,
        target_lang: str,
        service_name: str,
        endpoints: List[Dict[str, Any]]
    ) -> str:
        """Synthesize idiomatic server routing adapter in Python, TypeScript, or Go."""
        lang = target_lang.lower()
        clean_svc = self._normalize_identifier(service_name)

        if lang == "python":
            lines = [
                '"""FastAPI Server Router synthesized by Agtoosa2."""',
                "",
                "from typing import Any, Dict",
                "from fastapi import APIRouter, HTTPException, Depends",
                "from pydantic import BaseModel",
                "",
                f'router = APIRouter(prefix="/{service_name}", tags=["{service_name}"])',
                "",
                "class StandardResponse(BaseModel):",
                "    success: bool = True",
                "    message: str = 'Success'",
                "    data: Dict[str, Any] = {}",
                ""
            ]
            target_eps = endpoints or [{"name": "health", "metadata": {"method": "GET", "route": "/health"}}]
            for ep in target_eps:
                method, route, op_id = self._normalize_route_and_method(ep)
                fn_name = op_id.lower()
                lines.append(f'@router.{method.lower()}("{route}", response_model=StandardResponse)')
                lines.append(f"async def {fn_name}() -> StandardResponse:")
                lines.append(f'    """{ep.get("docstring") or op_id} handler."""')
                lines.append(f'    return StandardResponse(success=True, message="{op_id} executed successfully")')
                lines.append("")
            return "\n".join(lines)

        elif lang in ("typescript", "ts"):
            lines = [
                '/** Express.js Router Adapter synthesized by Agtoosa2. */',
                "import { Router, Request, Response } from 'express';",
                "",
                f"export const {service_name}Router = Router();",
                "",
                "export interface StandardResponse {",
                "  success: boolean;",
                "  message: string;",
                "  data?: Record<string, any>;",
                "}",
                ""
            ]
            target_eps = endpoints or [{"name": "health", "metadata": {"method": "GET", "route": "/health"}}]
            for ep in target_eps:
                method, route, op_id = self._normalize_route_and_method(ep)
                ts_route = route.replace("{", ":").replace("}", "")
                lines.append(f"{service_name}Router.{method.lower()}('{ts_route}', async (req: Request, res: Response) => {{")
                lines.append(f"  // Handler for {op_id}")
                lines.append("  res.json({")
                lines.append("    success: true,")
                lines.append(f"    message: '{op_id} executed successfully'")
                lines.append("  });")
                lines.append("});")
                lines.append("")
            return "\n".join(lines)

        elif lang == "go":
            lines = [
                f"// Package {service_name} HTTP server adapter synthesized by Agtoosa2.",
                f"package {service_name}",
                "",
                "import (",
                '    "encoding/json"',
                '    "net/http"',
                ")",
                "",
                "type StandardResponse struct {",
                '    Success bool   `json:"success"`',
                '    Message string `json:"message"`',
                "}",
                "",
                f"func Register{clean_svc}Routes(mux *http.ServeMux) {{",
            ]
            target_eps = endpoints or [{"name": "health", "metadata": {"method": "GET", "route": "/health"}}]
            for ep in target_eps:
                method, route, op_id = self._normalize_route_and_method(ep)
                go_route = route.replace("{", "").replace("}", "")
                lines.append(f'    mux.HandleFunc("{go_route}", func(w http.ResponseWriter, r *http.Request) {{')
                lines.append(f'        if r.Method != http.Method{method.capitalize()} {{')
                lines.append("            http.Error(w, \"Method Not Allowed\", http.StatusMethodNotAllowed)")
                lines.append("            return")
                lines.append("        }")
                lines.append("        w.Header().Set(\"Content-Type\", \"application/json\")")
                lines.append(f'        resp := StandardResponse{{Success: true, Message: "{op_id} executed successfully"}}')
                lines.append("        json.NewEncoder(w).Encode(resp)")
                lines.append("    })")
            lines.append("}")
            lines.append("")
            return "\n".join(lines)

        raise ValueError(f"Unsupported target language '{target_lang}'. Supported: python, typescript, go.")

    def synthesize_client_adapter(
        self,
        target_lang: str,
        service_name: str,
        endpoints: List[Dict[str, Any]]
    ) -> str:
        """Synthesize idiomatic client SDK adapter in Python, TypeScript, or Go."""
        lang = target_lang.lower()
        clean_svc = self._normalize_identifier(service_name)
        client_name = f"{clean_svc}Client"

        if lang == "python":
            lines = [
                '"""Async HTTP Client SDK synthesized by Agtoosa2."""',
                "",
                "from typing import Any, Dict, Optional",
                "import urllib.request",
                "import json",
                "",
                f"class {client_name}:",
                f'    """Client SDK for {clean_svc} microservice."""',
                "",
                f'    def __init__(self, base_url: str = "http://localhost:8000"):',
                "        self.base_url = base_url.rstrip('/')",
                ""
            ]
            target_eps = endpoints or [{"name": "health", "metadata": {"method": "GET", "route": "/health"}}]
            for ep in target_eps:
                method, route, op_id = self._normalize_route_and_method(ep)
                fn_name = op_id.lower()
                lines.append(f"    def {fn_name}(self, **kwargs: Any) -> Dict[str, Any]:")
                lines.append(f'        """Execute {method} {route}."""')
                lines.append(f'        url = f"{{self.base_url}}{route}"')
                lines.append('        req = urllib.request.Request(url, method="' + method + '")')
                lines.append("        with urllib.request.urlopen(req) as resp:")
                lines.append("            return json.loads(resp.read().decode('utf-8'))")
                lines.append("")
            return "\n".join(lines)

        elif lang in ("typescript", "ts"):
            lines = [
                '/** TypeScript Client SDK synthesized by Agtoosa2. */',
                "",
                f"export class {client_name} {{",
                f"  constructor(private readonly baseUrl: string = 'http://localhost:8000') {{}}",
                ""
            ]
            target_eps = endpoints or [{"name": "health", "metadata": {"method": "GET", "route": "/health"}}]
            for ep in target_eps:
                method, route, op_id = self._normalize_route_and_method(ep)
                fn_name = op_id[0].lower() + op_id[1:]
                lines.append(f"  async {fn_name}(payload?: Record<string, any>): Promise<any> {{")
                lines.append(f"    const url = `${{this.baseUrl}}{route}`;")
                lines.append(f"    const res = await fetch(url, {{")
                lines.append(f"      method: '{method}',")
                lines.append("      headers: { 'Content-Type': 'application/json' },")
                if method in ("POST", "PUT", "PATCH"):
                    lines.append("      body: payload ? JSON.stringify(payload) : undefined")
                lines.append("    });")
                lines.append("    return res.json();")
                lines.append("  }")
                lines.append("")
            lines.append("}")
            return "\n".join(lines)

        elif lang == "go":
            lines = [
                f"// Package {service_name} client SDK synthesized by Agtoosa2.",
                f"package {service_name}",
                "",
                "import (",
                '    "encoding/json"',
                '    "net/http"',
                '    "strings"',
                ")",
                "",
                f"type {client_name} struct {{",
                "    BaseURL    string",
                "    HTTPClient *http.Client",
                "}",
                "",
                f"func New{client_name}(baseURL string) *{client_name} {{",
                f"    return &{client_name}{{",
                "        BaseURL: strings.TrimRight(baseURL, \"/\"),",
                "        HTTPClient: http.DefaultClient,",
                "    }",
                "}",
                ""
            ]
            target_eps = endpoints or [{"name": "health", "metadata": {"method": "GET", "route": "/health"}}]
            for ep in target_eps:
                method, route, op_id = self._normalize_route_and_method(ep)
                lines.append(f"func (c *{client_name}) {op_id}() (*StandardResponse, error) {{")
                lines.append(f'    req, err := http.NewRequest("{method}", c.BaseURL+"{route}", nil)')
                lines.append("    if err != nil { return nil, err }")
                lines.append("    resp, err := c.HTTPClient.Do(req)")
                lines.append("    if err != nil { return nil, err }")
                lines.append("    defer resp.Body.Close()")
                lines.append("    var result StandardResponse")
                lines.append("    if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {")
                lines.append("        return nil, err")
                lines.append("    }")
                lines.append("    return &result, nil")
                lines.append("}")
                lines.append("")
            return "\n".join(lines)

        raise ValueError(f"Unsupported target language '{target_lang}'. Supported: python, typescript, go.")

    def synthesize_microservice_bundle(
        self,
        service_name: str,
        output_dir: Path,
        target_lang: str = "python",
        format_type: str = "all"
    ) -> Dict[str, str]:
        """Synthesize and write all requested microservice artifacts to the target directory."""
        output_dir.mkdir(parents=True, exist_ok=True)
        inferred_name, endpoints, schemas = self.discover_service_endpoints(service_name)
        svc_name = service_name or inferred_name

        results: Dict[str, str] = {}

        # 1. Protobuf v3
        if format_type in ("proto", "all"):
            proto_content = self.synthesize_proto(svc_name, endpoints, schemas)
            proto_path = output_dir / f"{svc_name}.proto"
            proto_path.write_text(proto_content, encoding="utf-8")
            results[proto_path.name] = str(proto_path)

        # 2. OpenAPI 3.0
        if format_type in ("openapi", "all"):
            openapi_spec = self.synthesize_openapi(svc_name, endpoints, schemas)
            openapi_path = output_dir / "openapi.json"
            openapi_path.write_text(json.dumps(openapi_spec, indent=2), encoding="utf-8")
            results[openapi_path.name] = str(openapi_path)

        # 3. Code Adapters
        if format_type in ("code", "all"):
            server_code = self.synthesize_server_adapter(target_lang, svc_name, endpoints)
            client_code = self.synthesize_client_adapter(target_lang, svc_name, endpoints)

            ext_map = {"python": ".py", "typescript": ".ts", "ts": ".ts", "go": ".go"}
            ext = ext_map.get(target_lang.lower(), ".txt")

            server_path = output_dir / f"{svc_name}_server{ext}"
            server_path.write_text(server_code, encoding="utf-8")
            results[server_path.name] = str(server_path)

            client_path = output_dir / f"{svc_name}_client{ext}"
            client_path.write_text(client_code, encoding="utf-8")
            results[client_path.name] = str(client_path)

        return results
